FROM golang:1.25 AS build

COPY go.mod go.sum /src/
COPY proto /src/proto
COPY processor /src/processor
COPY platform /src/platform


ENV CGO_ENABLED=0
RUN cd /src && go build -o /processor processor/cmd/main.go

FROM scratch

COPY --from=build /processor /processor

ENTRYPOINT ["/processor", "-config", "/config.yaml"]