// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type RepoCache struct {
	ID          int32       `db:"id" json:"id"`
	Owner       string      `db:"owner" json:"owner"`
	Repo        string      `db:"repo" json:"repo"`
	FullName    pgtype.Text `db:"full_name" json:"full_name"`
	Description pgtype.Text `db:"description" json:"description"`
	Stars       pgtype.Int4 `db:"stars" json:"stars"`
	Forks       pgtype.Int4 `db:"forks" json:"forks"`
	Visibility  pgtype.Text `db:"visibility" json:"visibility"`
	CreatedAt   pgtype.Text `db:"created_at" json:"created_at"`
}

type Subscription struct {
	ID    int32  `db:"id" json:"id"`
	Owner string `db:"owner" json:"owner"`
	Repo  string `db:"repo" json:"repo"`
}
