// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSubscription = `-- name: CreateSubscription :exec
INSERT INTO subscriptions (owner, repo)
VALUES ($1, $2)
ON CONFLICT (owner, repo) DO NOTHING
`

type CreateSubscriptionParams struct {
	Owner string `db:"owner" json:"owner"`
	Repo  string `db:"repo" json:"repo"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) error {
	_, err := q.db.Exec(ctx, createSubscription, arg.Owner, arg.Repo)
	return err
}

const deleteAllSubscriptions = `-- name: DeleteAllSubscriptions :exec
TRUNCATE TABLE subscriptions RESTART IDENTITY
`

func (q *Queries) DeleteAllSubscriptions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllSubscriptions)
	return err
}

const getRepoFromCache = `-- name: GetRepoFromCache :one
SELECT id, owner, repo, full_name, description, stars, forks, visibility, created_at FROM repo_cache 
WHERE owner = $1 AND repo = $2
`

type GetRepoFromCacheParams struct {
	Owner string `db:"owner" json:"owner"`
	Repo  string `db:"repo" json:"repo"`
}

func (q *Queries) GetRepoFromCache(ctx context.Context, arg GetRepoFromCacheParams) (RepoCache, error) {
	row := q.db.QueryRow(ctx, getRepoFromCache, arg.Owner, arg.Repo)
	var i RepoCache
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Repo,
		&i.FullName,
		&i.Description,
		&i.Stars,
		&i.Forks,
		&i.Visibility,
		&i.CreatedAt,
	)
	return i, err
}

const listSubscriptions = `-- name: ListSubscriptions :many
SELECT owner, repo FROM subscriptions ORDER BY id
`

type ListSubscriptionsRow struct {
	Owner string `db:"owner" json:"owner"`
	Repo  string `db:"repo" json:"repo"`
}

func (q *Queries) ListSubscriptions(ctx context.Context) ([]ListSubscriptionsRow, error) {
	rows, err := q.db.Query(ctx, listSubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSubscriptionsRow
	for rows.Next() {
		var i ListSubscriptionsRow
		if err := rows.Scan(&i.Owner, &i.Repo); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRepoCache = `-- name: UpsertRepoCache :exec
INSERT INTO repo_cache (owner, repo, full_name, description, stars, forks, visibility, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (owner, repo) DO UPDATE SET
    full_name         = EXCLUDED.full_name,
    description       = EXCLUDED.description,
    stars             = EXCLUDED.stars,
    forks             = EXCLUDED.forks,
    visibility        = EXCLUDED.visibility,
    created_at        = EXCLUDED.created_at
WHERE repo_cache.id IS NOT NULL
`

type UpsertRepoCacheParams struct {
	Owner       string      `db:"owner" json:"owner"`
	Repo        string      `db:"repo" json:"repo"`
	FullName    pgtype.Text `db:"full_name" json:"full_name"`
	Description pgtype.Text `db:"description" json:"description"`
	Stars       pgtype.Int4 `db:"stars" json:"stars"`
	Forks       pgtype.Int4 `db:"forks" json:"forks"`
	Visibility  pgtype.Text `db:"visibility" json:"visibility"`
	CreatedAt   pgtype.Text `db:"created_at" json:"created_at"`
}

func (q *Queries) UpsertRepoCache(ctx context.Context, arg UpsertRepoCacheParams) error {
	_, err := q.db.Exec(ctx, upsertRepoCache,
		arg.Owner,
		arg.Repo,
		arg.FullName,
		arg.Description,
		arg.Stars,
		arg.Forks,
		arg.Visibility,
		arg.CreatedAt,
	)
	return err
}
