// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/repository.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRepoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRepoRequest) Reset() {
	*x = GetRepoRequest{}
	mi := &file_proto_repository_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRepoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRepoRequest) ProtoMessage() {}

func (x *GetRepoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_repository_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRepoRequest.ProtoReflect.Descriptor instead.
func (*GetRepoRequest) Descriptor() ([]byte, []int) {
	return file_proto_repository_proto_rawDescGZIP(), []int{0}
}

func (x *GetRepoRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *GetRepoRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetRepoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Stars         int64                  `protobuf:"varint,3,opt,name=stars,proto3" json:"stars,omitempty"`
	Forks         int64                  `protobuf:"varint,4,opt,name=forks,proto3" json:"forks,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRepoResponse) Reset() {
	*x = GetRepoResponse{}
	mi := &file_proto_repository_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRepoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRepoResponse) ProtoMessage() {}

func (x *GetRepoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_repository_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRepoResponse.ProtoReflect.Descriptor instead.
func (*GetRepoResponse) Descriptor() ([]byte, []int) {
	return file_proto_repository_proto_rawDescGZIP(), []int{1}
}

func (x *GetRepoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetRepoResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetRepoResponse) GetStars() int64 {
	if x != nil {
		return x.Stars
	}
	return 0
}

func (x *GetRepoResponse) GetForks() int64 {
	if x != nil {
		return x.Forks
	}
	return 0
}

func (x *GetRepoResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_proto_repository_proto protoreflect.FileDescriptor

const file_proto_repository_proto_rawDesc = "" +
	"\n" +
	"\x16proto/repository.proto\x12\x03api\":\n" +
	"\x0eGetRepoRequest\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x92\x01\n" +
	"\x0fGetRepoResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x14\n" +
	"\x05stars\x18\x03 \x01(\x03R\x05stars\x12\x14\n" +
	"\x05forks\x18\x04 \x01(\x03R\x05forks\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt2I\n" +
	"\x11RepositoryService\x124\n" +
	"\aGetRepo\x12\x13.api.GetRepoRequest\x1a\x14.api.GetRepoResponseB\x0fZ\r./pkg/api;apib\x06proto3"

var (
	file_proto_repository_proto_rawDescOnce sync.Once
	file_proto_repository_proto_rawDescData []byte
)

func file_proto_repository_proto_rawDescGZIP() []byte {
	file_proto_repository_proto_rawDescOnce.Do(func() {
		file_proto_repository_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_repository_proto_rawDesc), len(file_proto_repository_proto_rawDesc)))
	})
	return file_proto_repository_proto_rawDescData
}

var file_proto_repository_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_repository_proto_goTypes = []any{
	(*GetRepoRequest)(nil),  // 0: api.GetRepoRequest
	(*GetRepoResponse)(nil), // 1: api.GetRepoResponse
}
var file_proto_repository_proto_depIdxs = []int32{
	0, // 0: api.RepositoryService.GetRepo:input_type -> api.GetRepoRequest
	1, // 1: api.RepositoryService.GetRepo:output_type -> api.GetRepoResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_repository_proto_init() }
func file_proto_repository_proto_init() {
	if File_proto_repository_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_repository_proto_rawDesc), len(file_proto_repository_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_repository_proto_goTypes,
		DependencyIndexes: file_proto_repository_proto_depIdxs,
		MessageInfos:      file_proto_repository_proto_msgTypes,
	}.Build()
	File_proto_repository_proto = out.File
	file_proto_repository_proto_goTypes = nil
	file_proto_repository_proto_depIdxs = nil
}
