-- Create subscriptions table
CREATE TABLE IF NOT EXISTS subscriptions (
    id         SERIAL PRIMARY KEY,
    owner      VARCHAR(255) NOT NULL,
    repo       VARCHAR(255) NOT NULL,

    UNIQUE (owner, repo)
);

CREATE INDEX ON subscriptions (owner, repo);

-- Create repo_cache table
CREATE TABLE IF NOT EXISTS repo_cache (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner             VARCHAR(255) NOT NULL,
    repo              VARCHAR(255) NOT NULL,
    full_name         VARCHAR(255),
    description       TEXT,
    stars             INTEGER,
    forks             INTEGER,
    visibility        VARCHAR(50),
    created_at        VARCHAR(100),

    UNIQUE (owner, repo)
);

CREATE INDEX ON repo_cache (owner, repo);