-- Fix repo_cache table: change id to GENERATED BY DEFAULT AS IDENTITY
-- This allows the column to be auto-generated but also allows explicit values

ALTER TABLE repo_cache ALTER COLUMN id DROP DEFAULT;
ALTER TABLE repo_cache ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
