// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: processor/processor.proto

package processorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetInfoRepoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repo          string                 `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	Owner         string                 `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoRepoRequest) Reset() {
	*x = GetInfoRepoRequest{}
	mi := &file_processor_processor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoRepoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoRepoRequest) ProtoMessage() {}

func (x *GetInfoRepoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_processor_processor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoRepoRequest.ProtoReflect.Descriptor instead.
func (*GetInfoRepoRequest) Descriptor() ([]byte, []int) {
	return file_processor_processor_proto_rawDescGZIP(), []int{0}
}

func (x *GetInfoRepoRequest) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *GetInfoRepoRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

type GetInfoRepoResponce struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fullname      string                 `protobuf:"bytes,1,opt,name=fullname,proto3" json:"fullname,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Stargazers    uint64                 `protobuf:"varint,3,opt,name=stargazers,proto3" json:"stargazers,omitempty"`
	Forks         uint64                 `protobuf:"varint,4,opt,name=forks,proto3" json:"forks,omitempty"`
	Createdat     string                 `protobuf:"bytes,5,opt,name=createdat,proto3" json:"createdat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoRepoResponce) Reset() {
	*x = GetInfoRepoResponce{}
	mi := &file_processor_processor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoRepoResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoRepoResponce) ProtoMessage() {}

func (x *GetInfoRepoResponce) ProtoReflect() protoreflect.Message {
	mi := &file_processor_processor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoRepoResponce.ProtoReflect.Descriptor instead.
func (*GetInfoRepoResponce) Descriptor() ([]byte, []int) {
	return file_processor_processor_proto_rawDescGZIP(), []int{1}
}

func (x *GetInfoRepoResponce) GetFullname() string {
	if x != nil {
		return x.Fullname
	}
	return ""
}

func (x *GetInfoRepoResponce) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetInfoRepoResponce) GetStargazers() uint64 {
	if x != nil {
		return x.Stargazers
	}
	return 0
}

func (x *GetInfoRepoResponce) GetForks() uint64 {
	if x != nil {
		return x.Forks
	}
	return 0
}

func (x *GetInfoRepoResponce) GetCreatedat() string {
	if x != nil {
		return x.Createdat
	}
	return ""
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_processor_processor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_processor_processor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_processor_processor_proto_rawDescGZIP(), []int{2}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reply         string                 `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_processor_processor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_processor_processor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_processor_processor_proto_rawDescGZIP(), []int{3}
}

func (x *PingResponse) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

var File_processor_processor_proto protoreflect.FileDescriptor

const file_processor_processor_proto_rawDesc = "" +
	"\n" +
	"\x19processor/processor.proto\x12\x0fprocessor.proto\">\n" +
	"\x12GetInfoRepoRequest\x12\x12\n" +
	"\x04repo\x18\x01 \x01(\tR\x04repo\x12\x14\n" +
	"\x05owner\x18\x02 \x01(\tR\x05owner\"\xa7\x01\n" +
	"\x13GetInfoRepoResponce\x12\x1a\n" +
	"\bfullname\x18\x01 \x01(\tR\bfullname\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"stargazers\x18\x03 \x01(\x04R\n" +
	"stargazers\x12\x14\n" +
	"\x05forks\x18\x04 \x01(\x04R\x05forks\x12\x1c\n" +
	"\tcreatedat\x18\x05 \x01(\tR\tcreatedat\"\r\n" +
	"\vPingRequest\"$\n" +
	"\fPingResponse\x12\x14\n" +
	"\x05reply\x18\x01 \x01(\tR\x05reply2\xaa\x01\n" +
	"\tProcessor\x12X\n" +
	"\vGetInfoRepo\x12#.processor.proto.GetInfoRepoRequest\x1a$.processor.proto.GetInfoRepoResponce\x12C\n" +
	"\x04Ping\x12\x1c.processor.proto.PingRequest\x1a\x1d.processor.proto.PingResponseB\xa9\x01\n" +
	"\x13com.processor.protoB\x0eProcessorProtoP\x01Z%repo-stat/proto/processor;processorpb\xa2\x02\x03PPX\xaa\x02\x0fProcessor.Proto\xca\x02\x0fProcessor\\Proto\xe2\x02\x1bProcessor\\Proto\\GPBMetadata\xea\x02\x10Processor::Protob\x06proto3"

var (
	file_processor_processor_proto_rawDescOnce sync.Once
	file_processor_processor_proto_rawDescData []byte
)

func file_processor_processor_proto_rawDescGZIP() []byte {
	file_processor_processor_proto_rawDescOnce.Do(func() {
		file_processor_processor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_processor_processor_proto_rawDesc), len(file_processor_processor_proto_rawDesc)))
	})
	return file_processor_processor_proto_rawDescData
}

var file_processor_processor_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_processor_processor_proto_goTypes = []any{
	(*GetInfoRepoRequest)(nil),  // 0: processor.proto.GetInfoRepoRequest
	(*GetInfoRepoResponce)(nil), // 1: processor.proto.GetInfoRepoResponce
	(*PingRequest)(nil),         // 2: processor.proto.PingRequest
	(*PingResponse)(nil),        // 3: processor.proto.PingResponse
}
var file_processor_processor_proto_depIdxs = []int32{
	0, // 0: processor.proto.Processor.GetInfoRepo:input_type -> processor.proto.GetInfoRepoRequest
	2, // 1: processor.proto.Processor.Ping:input_type -> processor.proto.PingRequest
	1, // 2: processor.proto.Processor.GetInfoRepo:output_type -> processor.proto.GetInfoRepoResponce
	3, // 3: processor.proto.Processor.Ping:output_type -> processor.proto.PingResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_processor_processor_proto_init() }
func file_processor_processor_proto_init() {
	if File_processor_processor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_processor_processor_proto_rawDesc), len(file_processor_processor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_processor_processor_proto_goTypes,
		DependencyIndexes: file_processor_processor_proto_depIdxs,
		MessageInfos:      file_processor_processor_proto_msgTypes,
	}.Build()
	File_processor_processor_proto = out.File
	file_processor_processor_proto_goTypes = nil
	file_processor_processor_proto_depIdxs = nil
}
