services:

  collector:
    build:
      context: .
      dockerfile: ./collector/cmd/Dockerfile
    ports:
      - "8082:8082"
  
  apigateway:
    build:
      context: .
      dockerfile: ./apigateway/cmd/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - collector