services:
  collector:
    build:
      context: .
      dockerfile: Dockerfile
      network: host  
      args:
        - SERVICE_PATH=collector
    container_name: collector-service
    ports:
      - "50051:50051"
    restart: always

  gateway:
    build:
      context: .
      dockerfile: Dockerfile
      network: host  
      args:
        - SERVICE_PATH=gateway
    container_name: gateway-service
    ports:
      - "8080:8080"
    environment:
      - COLLECTOR_ADDR=collector:50051
    depends_on:
      - collector
    restart: always
