// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

type Subscription struct {
	ID    int32  `db:"id" json:"id"`
	Owner string `db:"owner" json:"owner"`
	Repo  string `db:"repo" json:"repo"`
}
