// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"
)

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (owner, repo)
VALUES ($1, $2)
RETURNING id, owner, repo
`

type CreateSubscriptionParams struct {
	Owner string `db:"owner" json:"owner"`
	Repo  string `db:"repo" json:"repo"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, createSubscription, arg.Owner, arg.Repo)
	var i Subscription
	err := row.Scan(&i.ID, &i.Owner, &i.Repo)
	return i, err
}

const deleteSubscription = `-- name: DeleteSubscription :exec
DELETE FROM subscriptions
WHERE owner = $1 AND repo = $2
`

type DeleteSubscriptionParams struct {
	Owner string `db:"owner" json:"owner"`
	Repo  string `db:"repo" json:"repo"`
}

func (q *Queries) DeleteSubscription(ctx context.Context, arg DeleteSubscriptionParams) error {
	_, err := q.db.Exec(ctx, deleteSubscription, arg.Owner, arg.Repo)
	return err
}

const existsSubscription = `-- name: ExistsSubscription :one
SELECT EXISTS (
    SELECT 1 
    FROM subscriptions 
    WHERE owner = $1 AND repo = $2
)
`

type ExistsSubscriptionParams struct {
	Owner string `db:"owner" json:"owner"`
	Repo  string `db:"repo" json:"repo"`
}

func (q *Queries) ExistsSubscription(ctx context.Context, arg ExistsSubscriptionParams) (bool, error) {
	row := q.db.QueryRow(ctx, existsSubscription, arg.Owner, arg.Repo)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getSubscription = `-- name: GetSubscription :one
SELECT id, owner, repo
FROM subscriptions
WHERE owner = $1 AND repo = $2
`

type GetSubscriptionParams struct {
	Owner string `db:"owner" json:"owner"`
	Repo  string `db:"repo" json:"repo"`
}

func (q *Queries) GetSubscription(ctx context.Context, arg GetSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscription, arg.Owner, arg.Repo)
	var i Subscription
	err := row.Scan(&i.ID, &i.Owner, &i.Repo)
	return i, err
}

const listSubscriptions = `-- name: ListSubscriptions :many
SELECT id, owner, repo
FROM subscriptions
ORDER BY id
`

func (q *Queries) ListSubscriptions(ctx context.Context) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, listSubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscription
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(&i.ID, &i.Owner, &i.Repo); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
