// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/proto/client.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Эти коды маппятся в gRPC status codes в handler слое
type ErrorCode int32

const (
	ErrorCode_ERROR_CODE_UNSPECIFIED ErrorCode = 0 // Нет ошибки
	// Клиентские ошибки (4xx)
	ErrorCode_ERROR_CODE_NOT_FOUND     ErrorCode = 404 // Репозиторий не найден
	ErrorCode_ERROR_CODE_UNAUTHORIZED  ErrorCode = 401 // Требуется авторизация
	ErrorCode_ERROR_CODE_FORBIDDEN     ErrorCode = 403 // Доступ запрещён
	ErrorCode_ERROR_CODE_RATE_LIMITED  ErrorCode = 429 // Превышен лимит запросов
	ErrorCode_ERROR_CODE_INVALID_INPUT ErrorCode = 400 // Некорректные входные данные
	// Серверные ошибки (5xx)
	ErrorCode_ERROR_CODE_INTERNAL       ErrorCode = 500 // Внутренняя ошибка сервера
	ErrorCode_ERROR_CODE_UPSTREAM_ERROR ErrorCode = 502 // Ошибка при вызове GitHub API
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0:   "ERROR_CODE_UNSPECIFIED",
		404: "ERROR_CODE_NOT_FOUND",
		401: "ERROR_CODE_UNAUTHORIZED",
		403: "ERROR_CODE_FORBIDDEN",
		429: "ERROR_CODE_RATE_LIMITED",
		400: "ERROR_CODE_INVALID_INPUT",
		500: "ERROR_CODE_INTERNAL",
		502: "ERROR_CODE_UPSTREAM_ERROR",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNSPECIFIED":    0,
		"ERROR_CODE_NOT_FOUND":      404,
		"ERROR_CODE_UNAUTHORIZED":   401,
		"ERROR_CODE_FORBIDDEN":      403,
		"ERROR_CODE_RATE_LIMITED":   429,
		"ERROR_CODE_INVALID_INPUT":  400,
		"ERROR_CODE_INTERNAL":       500,
		"ERROR_CODE_UPSTREAM_ERROR": 502,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_client_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_api_proto_client_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_client_proto_rawDescGZIP(), []int{0}
}

// Запрос: получить репозиторий по полной URL-ссылке
// Пример: "https://github.com/torvalds/linux"
type GetRepositoryByURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRepositoryByURLRequest) Reset() {
	*x = GetRepositoryByURLRequest{}
	mi := &file_api_proto_client_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRepositoryByURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRepositoryByURLRequest) ProtoMessage() {}

func (x *GetRepositoryByURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_client_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRepositoryByURLRequest.ProtoReflect.Descriptor instead.
func (*GetRepositoryByURLRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_client_proto_rawDescGZIP(), []int{0}
}

func (x *GetRepositoryByURLRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// Ответ: содержит данные репозитория или ошибку
type GetRepositoryResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Repository *Repository            `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	// Код ошибки (если произошла ошибка)
	// 0 = нет ошибки, >0 = код ошибки (см. ErrorCodes)
	ErrorCode     int32  `protobuf:"varint,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRepositoryResponse) Reset() {
	*x = GetRepositoryResponse{}
	mi := &file_api_proto_client_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRepositoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRepositoryResponse) ProtoMessage() {}

func (x *GetRepositoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_client_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRepositoryResponse.ProtoReflect.Descriptor instead.
func (*GetRepositoryResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_client_proto_rawDescGZIP(), []int{1}
}

func (x *GetRepositoryResponse) GetRepository() *Repository {
	if x != nil {
		return x.Repository
	}
	return nil
}

func (x *GetRepositoryResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *GetRepositoryResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Сущность репозитория (соответствует Repository из ДЗ №1)
type Repository struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FullName      string                 `protobuf:"bytes,1,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Stars         int32                  `protobuf:"varint,2,opt,name=stars,proto3" json:"stars,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Forks         int64                  `protobuf:"varint,4,opt,name=forks,proto3" json:"forks,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Language      string                 `protobuf:"bytes,6,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Repository) Reset() {
	*x = Repository{}
	mi := &file_api_proto_client_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Repository) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Repository) ProtoMessage() {}

func (x *Repository) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_client_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Repository.ProtoReflect.Descriptor instead.
func (*Repository) Descriptor() ([]byte, []int) {
	return file_api_proto_client_proto_rawDescGZIP(), []int{2}
}

func (x *Repository) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *Repository) GetStars() int32 {
	if x != nil {
		return x.Stars
	}
	return 0
}

func (x *Repository) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Repository) GetForks() int64 {
	if x != nil {
		return x.Forks
	}
	return 0
}

func (x *Repository) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Repository) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

var File_api_proto_client_proto protoreflect.FileDescriptor

const file_api_proto_client_proto_rawDesc = "" +
	"\n" +
	"\x16api/proto/client.proto\x12\tcollector\"-\n" +
	"\x19GetRepositoryByURLRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\x92\x01\n" +
	"\x15GetRepositoryResponse\x125\n" +
	"\n" +
	"repository\x18\x01 \x01(\v2\x15.collector.RepositoryR\n" +
	"repository\x12\x1d\n" +
	"\n" +
	"error_code\x18\x02 \x01(\x05R\terrorCode\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"\xb2\x01\n" +
	"\n" +
	"Repository\x12\x1b\n" +
	"\tfull_name\x18\x01 \x01(\tR\bfullName\x12\x14\n" +
	"\x05stars\x18\x02 \x01(\x05R\x05stars\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05forks\x18\x04 \x01(\x03R\x05forks\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1a\n" +
	"\blanguage\x18\x06 \x01(\tR\blanguage*\xf2\x01\n" +
	"\tErrorCode\x12\x1a\n" +
	"\x16ERROR_CODE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x14ERROR_CODE_NOT_FOUND\x10\x94\x03\x12\x1c\n" +
	"\x17ERROR_CODE_UNAUTHORIZED\x10\x91\x03\x12\x19\n" +
	"\x14ERROR_CODE_FORBIDDEN\x10\x93\x03\x12\x1c\n" +
	"\x17ERROR_CODE_RATE_LIMITED\x10\xad\x03\x12\x1d\n" +
	"\x18ERROR_CODE_INVALID_INPUT\x10\x90\x03\x12\x18\n" +
	"\x13ERROR_CODE_INTERNAL\x10\xf4\x03\x12\x1e\n" +
	"\x19ERROR_CODE_UPSTREAM_ERROR\x10\xf6\x032p\n" +
	"\x10CollectorService\x12\\\n" +
	"\x12GetRepositoryByURL\x12$.collector.GetRepositoryByURLRequest\x1a .collector.GetRepositoryResponseB\x13Z\x11сollector/api/pbb\x06proto3"

var (
	file_api_proto_client_proto_rawDescOnce sync.Once
	file_api_proto_client_proto_rawDescData []byte
)

func file_api_proto_client_proto_rawDescGZIP() []byte {
	file_api_proto_client_proto_rawDescOnce.Do(func() {
		file_api_proto_client_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_client_proto_rawDesc), len(file_api_proto_client_proto_rawDesc)))
	})
	return file_api_proto_client_proto_rawDescData
}

var file_api_proto_client_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_client_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_proto_client_proto_goTypes = []any{
	(ErrorCode)(0),                    // 0: collector.ErrorCode
	(*GetRepositoryByURLRequest)(nil), // 1: collector.GetRepositoryByURLRequest
	(*GetRepositoryResponse)(nil),     // 2: collector.GetRepositoryResponse
	(*Repository)(nil),                // 3: collector.Repository
}
var file_api_proto_client_proto_depIdxs = []int32{
	3, // 0: collector.GetRepositoryResponse.repository:type_name -> collector.Repository
	1, // 1: collector.CollectorService.GetRepositoryByURL:input_type -> collector.GetRepositoryByURLRequest
	2, // 2: collector.CollectorService.GetRepositoryByURL:output_type -> collector.GetRepositoryResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_client_proto_init() }
func file_api_proto_client_proto_init() {
	if File_api_proto_client_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_client_proto_rawDesc), len(file_api_proto_client_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_client_proto_goTypes,
		DependencyIndexes: file_api_proto_client_proto_depIdxs,
		EnumInfos:         file_api_proto_client_proto_enumTypes,
		MessageInfos:      file_api_proto_client_proto_msgTypes,
	}.Build()
	File_api_proto_client_proto = out.File
	file_api_proto_client_proto_goTypes = nil
	file_api_proto_client_proto_depIdxs = nil
}
