name: Go CI

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  build-Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Find and build all Go modules
        run: |
          for dir in $(find . -name "go.mod" -exec dirname {} \;); do
            echo "Building $dir"
            (cd $dir && go build -v ./...)
          done

      - name: Find and test all Go modules
        run: |
          for dir in $(find . -name "go.mod" -exec dirname {} \;); do
            echo "Testing $dir"
            (cd $dir && go test -v ./...)
          done

  build-Windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Find and build all Go modules
        shell: bash
        run: |
          for dir in $(find . -name "go.mod" -exec dirname {} \;); do
            echo "Building $dir"
            (cd $dir && go build -v ./...)
          done

      - name: Find and test all Go modules
        shell: bash
        run: |
          for dir in $(find . -name "go.mod" -exec dirname {} \;); do
            echo "Testing $dir"
            (cd $dir && go test -v ./...)
          done